version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      my_network:
        aliases:
          - db
    hostname: db
    container_name: db

  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/rails_app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      my_network:
        aliases:
          - db
    hostname: web
    container_name: web

networks:
  my_network:
    driver: bridge